### PR TITLE
Updated to latest version

### PR DESCRIPTION
**Pull request by iStagnant**
I updated the mod to the latest game version and fixed the issues that update cause.

And since i learned JS just for this project I ask of you to see if i implemented `MEGA: Remove new 1.1.6 rendering range of 30 tiles` correctly since it was changed from a conditional operator to a if else statement, and maybe try the mod to check if there's any bugs since I'm not far enough into the game to try all the features (like buy T10).

And lastly after merging this pull request, you should probably look into `git filter-repo` to delete the IP content from the history of the repo since you can still look at it when checking out previous commits and it adds a lot of size to the repo, it's like 120MB i think of wasted data.

### CODE REVIEW

**Comment by hyaguitos** [comment]
hi, can you please release an apk? the release section is empty, and i don't have a computer to use apk tool

**Comment by iStagnant** [comment]
> hi, can you please release an apk? the release section is empty, and i don't have a computer to use apk tool

Unfortunately I can't, the reason the release section is empty is because themegafuji probably got a notice from the hero of aethric creator because he's distributing a modified apk of his game which violates copyright laws.

But all hope is not lost you obviously have an android device so you can use termux. Sometime in the future i will update the readme to include how to build and install the game on android

**Comment by iStagnant** [comment]
I just got banned in the game and looking at previous issues, I can see that others have as well. I think it wasn't anti-cheat that banned me but the anti-cheat flagged me and then a manual reviewer banned me since I wasn't even playing when i was banned. And as such I will not continue working on this project since it's pointless if every person that's using will get banned.

**Comment by tuan51000** [comment]
how do i update the old version to the newest one?

**Comment by iStagnant** [comment]
> how do i update the old version to the newest one?

I wouldn't advise it since like I said you'll get banned eventually, but if you still want to do it:
1. Download latest apk from apkcombo for example
2. Download and decompile the apk using apktool
3. Find the game-\*.js (\* indicating anything), that's the file you'll be working with
4. In the same folder there be a bundle.idx rename it to bundle.html
5. Open the html in chrome and you'll be able to play it on pc and also debug the code
6. Press F12 and open the debbuger to pretty print the code
7. Everything that was added by themegafuji was labeled with a comment so look at what's before the added code to know where you should add it in the new code
8. After you added all the code compile and zipalign then sign the apk using apksigner, and you're done

If you don't know how to do any of these and are not willing to research how to do them, then this is not for you

**Comment by tuan51000** [comment]
cool i did it but i got ban but i been using the old one and haven't got ban yet

**Comment by tuan51000** [comment]
hey u got discord? mine is eternalz.

**Pull request closed without merging**
